# Generated by Django 5.0.7 on 2024-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='users',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
